pivot:
  master: 3.82.195.222
  port: 9191
  n_parallel: 1
  https: false
db:
  host: localhost
  port: 27017
  name: pivot
mesos:
  port: 5050
marathon:
  port: 8080
chronos:
  port: 9090
exhibitor:
  port: 8181
ceph:
  host: localhost
  port: 8080



