---
pivot:
  master: m1.dcos
  port: 9090
  n_parallel: 8
  scheduler: scheduler.plugin.location.LocationAwareApplianceScheduler
  ha: false
db:
  host: localhost
  port: 27017
mesos:
  port: 5050
marathon:
  port: 8080
chronos:
  port: 9090
exhibitor:
  port: 8181
irods:
  host: 54.236.240.212
  port: 8080


